package gpt.models.message;

import gpt.models.message.standard.MessageModel;
import lombok.Data;

import java.util.List;

/**
 * Class representing a GPT response object.
 * <p>
 * The fields of this class include:
 * - id: A string representing the ID of the response.
 * - object: A string representing the object type of the response.
 * - created: A double representing the timestamp of when the response was created.
 * - model: A string representing the GPT model used to generate the response.
 * - usage: An object representing the usage statistics for the GPT API.
 * - choices: A list of choices generated by the GPT model.
 */
@Data
public class MessageResponse {

    String id;
    String object;
    Double created;
    String model;
    Usage usage;
    List<Choices> choices;

    /**
     * Class representing the usage statistics for a GPT response object.
     * <p>
     * This class is annotated with @Data, which generates getters, setters, and other boilerplate code automatically.
     * <p>
     * The fields of this class include:
     * - prompt_tokens: A double representing the number of tokens used in the prompt for the GPT response.
     * - completion_tokens: A double representing the number of tokens used in the completion for the GPT response.
     * - total_tokens: A double representing the total number of tokens used in the GPT response.
     */
    @Data
    public static class Usage{
        Double prompt_tokens;
        Double completion_tokens;
        Double total_tokens;
    }

    /**
     * Class representing a choice generated by a GPT model.
     * <p>
     * This class is annotated with @Data, which generates getters, setters, and other boilerplate code automatically.
     * <p>
     * The fields of this class include:
     * - message: A Message object representing the generated message.
     * - finish_reason: A string representing the reason why the generation process finished.
     * - index: A double representing the index of the choice in the list of choices.
     */
    @Data
    public static class Choices {
        MessageModel message;
        String finish_reason;
        Double index;
    }
}
